server {
    listen 8888;

    root /var/www;

    location = / {
        return 302 /smart-stocker/portfolio.html;
    }

    location /smart-stocker/ {
        index portfolio.html;
        autoindex on;
        default_type text/html;
    }
}
